modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="xkdeco"
version="1.0.0"
displayName="XK's Deco"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://space.bilibili.com/5930630"
authors="XeKr"

[[dependencies.xkdeco]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




